### ISSUE TITLE
Firestore Problem

### ISSUE THREAD

**Issue by Rohankar123** [CharlyKeleb/SocialMedia-App#4]
Hey
Iam getting error when i create my new account :
cloud_firestore/permission-denied - The caller does not have permission to execute the specified operation

**Comment by Rohankar123** [comment]
I enabled 
google authentication 
Firestore
Database
Storage but still iam getting error

**Comment by Charles042** [comment]
What was the error on the console?

**Comment by tameryalcin** [comment]
I'm getting error 

/Firestore(12098): (21.7.1) [Firestore]: Write failed at users/h7Ky4qj6dRULxjCJBitfh13nYIs2: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}
